In [9]:
# Assignment 1 Ques 9

import numpy as np
import random

# User input values of m,n and p
m=int(input("Enter no of m "))
n=int(input("Enter no of n "))
p=int(input("Enter no of p "))

# Initializing matrix 1, matrix 2 and product matrix with zeros
mat1 = [[0 for i in range(n)] for j in range(m)]
mat2 = [[0 for i in range(p)] for j in range(n)]
prod1=  [[0 for i in range(p)] for j in range(m)]
prod2=  [[0 for i in range(p)] for j in range(m)]

# Generating matrix 1 with random values
for i in range(m):
    for j in range(n):
        mat1[i][j]=random.randint(-2,5)
        
# Generating matrix 2 with random values
for x in range(n):
    for y in range(p):
        mat2[x][y]=random.randint(-2,5)

# Printing matrix 1
print("\nMatrix 1 is: \n")

for m in mat1:
    print(m)
    
# Printing matrix 2
print("\nMatrix 2 is: \n")

for n in mat2:
    print(n)

# Calculating matrix product and storing answer in prod matrix

for i in range(len(mat1)):                        # i will vary from 0 to m-1
    for j in range(len(mat2[0])):                 # j will vary from 0 to p-1
        for k in range(len(mat2)):                # k will vary from 0 to n-1
            prod1[i][j]+=mat1[i][k]*mat2[k][j]

# Printing the product matrix
print("\nProduct of the two matrices is: \n")
for p in prod1:
    print(p)
    
# Calculating matrix product using built-in function
prod2=np.dot(mat1,mat2)

print("\nProduct of the two matrices using built-in function is: \n")
for p in prod2:
    print(p)


Enter no of m 3
Enter no of n 4
Enter no of p 5

Matrix 1 is: 

[0, -2, 4, 4]
[4, 3, 3, -1]
[4, 1, 5, 5]

Matrix 2 is: 

[4, 3, 3, 5, 3]
[-2, 4, 1, 0, 4]
[1, 5, -2, -2, 1]
[3, 5, 5, 3, 4]

Product of the two matrices is: 

[20, 32, 10, 4, 12]
[10, 34, 4, 11, 23]
[34, 66, 28, 25, 41]

Product of the two matrices using built-in function is: 

[20 32 10  4 12]
[10 34  4 11 23]
[34 66 28 25 41]
