In [4]:
# Assignment 1 Ques 7

import numpy

arr=[6,9,1,7,3,15,12,26,19,34,52,33,47,62,22] 

x=numpy.array(arr)      
index=numpy.argsort(x)               # 'index' will store the indices of sorted array
sorted=numpy.sort(x)                 # 'sorted' will store the array sorted in ascending order
  

print("Unsorted array:\n")
print(x)

print("\nSorted Array:\n")
print(sorted)

print("\nSorted indices:\n")
print(index)


Unsorted array:

[ 6  9  1  7  3 15 12 26 19 34 52 33 47 62 22]

Sorted Array:

[ 1  3  6  7  9 12 15 19 22 26 33 34 47 52 62]

Sorted indices:

[ 2  4  0  3  1  6  5  8 14  7 11  9 12 10 13]
